/* ============================================================
   Tweet → name / ticker / image choice.

   Image: reuse the tweet's first photo. Generation is an optional
   fallback (placeholder PNG) — we never invent a "generated by AI"
   success if no model is configured.
   ============================================================ */

const STOP = new Set([
  'the', 'of', 'and', 'for', 'a', 'to', 'in', 'is', 'on', 'it', 'my', 'me',
  'you', 'this', 'that', 'with', 'from', 'just', 'now', 'are', 'was', 'be',
  'at', 'as', 'or', 'an', 'by', 'not', 'but', 'so', 'if', 'we', 'they',
  'i', 'im', 'i\'m', 'its', 'it\'s', 'your', 'our', 'out', 'up', 'new',
  'have', 'has', 'had', 'will', 'can', 'all', 'about', 'what', 'when',
  'who', 'how', 'why', 'http', 'https', 'www', 'com', 'lol', 'lmao',
  'rt', 'amp',
]);

function cleanText(text) {
  return String(text || '')
    .replace(/https?:\/\/\S+/gi, ' ')
    .replace(/&amp;/g, '&')
    .replace(/[@#]/g, '')
    .replace(/[^\w\s$.'-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function wordsOf(text) {
  return cleanText(text)
    .split(/\s+/)
    .map(w => w.replace(/^\$/, ''))
    .filter(w => w.length >= 2 && !STOP.has(w.toLowerCase()) && !/^\d+$/.test(w));
}

function tickerFrom(seed) {
  const alnum = String(seed || '').replace(/[^a-zA-Z0-9]/g, '').toUpperCase();
  if (alnum.length >= 3 && alnum.length <= 10) return alnum;
  if (alnum.length > 10) return alnum.slice(0, 10);
  const padded = (alnum + 'XCOIN').slice(0, 4);
  return padded;
}

function pickTicker(tweet) {
  const words = wordsOf(tweet.text);
  const cashtag = (tweet.text.match(/\$([A-Za-z][A-Za-z0-9]{1,9})/) || [])[1];
  if (cashtag) return tickerFrom(cashtag);
  const ranked = [...words].sort((a, b) => {
    const score = (w) => {
      let s = w.length;
      if (/[A-Z]/.test(w) && w === w.toUpperCase() && w.length >= 3) s += 8;
      if (/^[A-Z]/.test(w) && w.length >= 4) s += 2;
      return s;
    };
    return score(b) - score(a);
  });
  if (ranked[0]) return tickerFrom(ranked[0]);
  if (tweet.author) return tickerFrom(tweet.author);
  return 'GROK';
}

function pickName(tweet) {
  const cleaned = cleanText(tweet.text);
  if (!cleaned) return tweet.author ? String(tweet.author).slice(0, 32) : 'untitled';
  const first = cleaned.split(/[.!\n]/)[0].trim();
  const name = (first || cleaned).slice(0, 32).trim();
  return name || 'untitled';
}

function pickImage(tweet) {
  const photo = (tweet.media || []).find(m => m.url && (m.type === 'photo' || m.type === 'animated_gif' || !m.type));
  const any = (tweet.media || []).find(m => m.url);
  const url = (photo || any || {}).url || null;
  return { imageUrl: url, imageSource: url ? 'tweet' : 'placeholder' };
}

function proposeFromTweet(tweet) {
  if (!tweet || typeof tweet !== 'object') throw new Error('tweet required');
  const name = pickName(tweet);
  const symbol = pickTicker(tweet);
  const { imageUrl, imageSource } = pickImage(tweet);
  const description = [
    cleanText(tweet.text).slice(0, 200) || name,
    tweet.url ? 'source: ' + tweet.url : null,
  ].filter(Boolean).join('\n');
  return {
    name,
    symbol,
    description: description.slice(0, 280),
    twitter: tweet.url || null,
    imageUrl,
    imageSource,
    tweetId: tweet.id || null,
    author: tweet.author || null,
  };
}

module.exports = {
  cleanText,
  tickerFrom,
  proposeFromTweet,
};
